### PR TITLE
fix(ctp): skip commit time when no active dry sha

### LINKED ISSUE #99: Gracefully handle empty active branch
If there's no hydrator.metadata in the active branch, the CTP controller currently fails with an error like this:

```
2024-11-04T15:33:44.793Z        INFO    Branch SHAs     {"controller": "changetransferpolicy", "controllerGroup": "promoter.argoproj.io", "controllerKind": "ChangeTransferPolicy", "ChangeTransferPolicy": {"name":"argocon-demo-environments-development-eadabead","namespace":"promoter-system"}, "namespace": "promoter-system", "name": "argocon-demo-environments-development-eadabead", "reconcileID": "ed437977-f5b0-4c19-8b09-5e277dcf1dfe", "branchShas": {"environments/development":{"Dry":"","Hydrated":"a126b37613c32213e03939a1b1556028ec9097ea"},"environments/development-next":{"Dry":"2ab072a32a4fd923604c40a2c14d986a66b7a359","Hydrated":"53e0a9ef8464fe2b987acd908173666c7a64d2d2"}}}
2024-11-04T15:33:44.794Z        ERROR   could not git show      {"controller": "changetransferpolicy", "controllerGroup": "promoter.argoproj.io", "controllerKind": "ChangeTransferPolicy", "ChangeTransferPolicy": {"name":"argocon-demo-environments-development-eadabead","namespace":"promoter-system"}, "namespace": "promoter-system", "name": "argocon-demo-environments-development-eadabead", "reconcileID": "ed437977-f5b0-4c19-8b09-5e277dcf1dfe", "gitError": "fatal: ambiguous argument '': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n", "error": "exit status 128"}
github.com/argoproj-labs/gitops-promoter/internal/git.(*GitOperations).GetShaTime
        /workspace/internal/git/git.go:180
github.com/argoproj-labs/gitops-promoter/internal/controller.(*ChangeTransferPolicyReconciler).calculateStatus
        /workspace/internal/controller/changetransferpolicy_controller.go:168
github.com/argoproj-labs/gitops-promoter/internal/controller.(*ChangeTransferPolicyReconciler).Reconcile
        /workspace/internal/controller/changetransferpolicy_controller.go:106
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224
```

Ideally the hydrator should take care of this. But at the least we should print a nicer error.

### PR DESCRIPTION
**Pull request by alexymantha**
See discussion here: https://github.com/argoproj-labs/gitops-promoter/issues/99#issuecomment-2756220224

Fixes #99

### CODE REVIEW

**Comment by zachaller** [comment]
The tests have passed which means I think means golang time lib must have handled this [check](https://github.com/argoproj-labs/gitops-promoter/blob/9ab86487365280cdb72ef7dc3d5119addabd3941/internal/controller/promotionstrategy_controller.go#L391) ok for activeCommitStatuses.

I have to think about if it makes sense to leave that empty or just set it to `time.Time{}` which which ends up being `0001-01-01 00:00:00 +0000 UTC`

I would also like to see how that time bubbles up to the promotion strategy with your change as well.

**Comment by alexymantha** [comment]
> I would also like to see how that time bubbles up to the promotion strategy with your change as well.

It shows up empty on the PromotionStrategy as well, similar to the ChangeTransferPolicy.
```yaml
  - active:
      commitStatus:
        phase: pending
        sha: pending
      dry: {}
      hydrated:
        commitTime: "2025-03-27T00:58:49Z"
        sha: 92036f137495cc5941c49883c606f0ab6640c7dc
```

I think that's reasonable, then when we use the zero value for the time will be `0001-01-01 00:00:00 +0000 UTC` as you said and an empty string for the SHA.

**Comment by zachaller** [comment]
I am not sure how you tested this but I am now sure that our current test cases will not cover the actually check for the merging of the PR, I think you should try to test this with a PromotionStrategy that has active checks enables and tries to merge the PR (aka set the activeCommistStatus checks to success), we would also want to construct a test that does not create the hydrator.metadata file, because currently it always does.

**Comment by alexymantha** [comment]
There is more details on how I tested in my comment here https://github.com/argoproj-labs/gitops-promoter/issues/99#issuecomment-2756220224. I mostly opened this to support the discussion there. I'm honestly surprised that the test are passing hahaha. If it makes sense, then I'd be happy to test it further and add the test cases

**Comment by zachaller** [comment]
Yea we would need that test, because we need to make sure it also passed this part of the code where it is used, https://github.com/argoproj-labs/gitops-promoter/blob/9ab86487365280cdb72ef7dc3d5119addabd3941/internal/controller/promotionstrategy_controller.go#L391 as well as anywhere else within the PS controller. So I would want to make sure that the PS controller is actually able to merge that PR with activeCommitStatuses configured on a previous environment.

**Comment by alexymantha** [comment]
Tested it locally and I was able to do a full promotion with activeCommitStatuses and automerge without any other changes. I'm working on adding test cases to cover that behavior, but I don't think any other logic change is required

File: internal/git/git.go [hunk 1]
```diff
@@ -139,6 +140,10 @@ func (g *GitOperations) GetBranchShas(ctx context.Context, branch string) (Branc
 	metadataFile := gitpaths.Get(g.gap.GetGitHttpsRepoUrl(*g.gitRepo)+g.pathContext) + "/hydrator.metadata"
 	jsonFile, err := os.Open(metadataFile)
 	if err != nil {
+		if errors.Is(err, os.ErrNotExist) {
```
Comment (alexymantha) [inline internal/git/git.go:150]: Needed since https://github.com/argoproj-labs/gitops-promoter/pull/250 was merged because the error is not handled anymore.

File: internal/controller/suite_test.go [hunk 2]
```diff
@@ -305,6 +305,73 @@ func startGitServer(gitStoragePath string) (string, *http.Server) {
 	return gitServerPortStr, server
 }
 
+func setupInitialTestGitRepoWithoutActiveMetadata(owner string, name string) {
```
Comment (crenshaw-dev) [inline internal/controller/suite_test.go:308]: Is this used? Not finding any references...

Comment (alexymantha) [reply internal/controller/suite_test.go:308]: It's in the `promotionstrategy_controller_test.go` file. GitHub collapses the file by default because the diff is too big, it might be why

**Review by crenshaw-dev — APPROVED** [review]
